runtime: php55
api_version: 1

handlers:
- url: /galileo-navionics-boating.ms
  script: galileo-navionics-boating.ms.php

- url: /galileo-navionics-sonar.ms
  script: galileo-navionics-sonar.ms.php

- url: /galileo-eniro-navionics.ms
  script: galileo-eniro-navionics.ms.php

- url: /navionics-boating-tile/\d+/\d+/\d+
  script: navionics-boating-tile.php

- url: /(.+\.ms)$
  static_files: \1
  upload: .+\.ms$
  mime_type: application/x-galileo
  http_headers:
      Content-Disposition: attachment

- url: /(.+\.png)$
  static_files: \1
  upload: .+\.png$

- url: /
  script: index.html
